# -*- coding: utf-8 -*-
"""Practical_3C.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S3NSFp7bBpRVIqJzOm-pbvlINv_ZElwt
"""

# PRACTICAL 3 - Utilities and Auditing
# 3C. AVERAGING OF DATA
# VIVEKSINGH NEGI - 23-SEP-2022
# UNIVERSITY DEPARTMENT OF INFORMATION TECHNO

import pandas as pd

InputFileName='/content/IP_DATA_CORE.csv'

IP_DATA_ALL=pd.read_csv(InputFileName,header=0,low_memory=False, usecols=['Country','Place Name','Latitude','Longitude'], encoding="latin-1")
IP_DATA_ALL.shape

IP_DATA_ALL.head()

IP_DATA_ALL.rename(columns={'Place Name': 'Place_Name'}, inplace=True)
IP_DATA_ALL.head()

AllData=IP_DATA_ALL[['Country', 'Place_Name','Latitude']]
print(AllData)

MeanData=AllData.groupby(['Country', 'Place_Name'])['Latitude'].mean()
print(MeanData)

OutputData=MeanData
sOutputFileName='Averaging_Data.csv'
OutputData.to_csv(sOutputFileName, index = True)