# -*- coding: utf-8 -*-
"""Practical_2A.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W_kYvD0DpqzyJQzZAmfunq24Vqqo_PGh
"""

# PRACTICAL 2 - CONVERTING DATA TO HORUS
# 2A - CSV TO HORUS
# VIVEKSINGH NEGI - 13-SEP-2022
# UNIVERSITY DEPARTMENT OF INFORMATION TECHNOLOGY

# IMPORTING LIBRARIES 
import pandas as pd

# OPENING THE FILE
fname = '/content/Country_Code.csv'
fname

# READING DATE FROM THE FILE
in_data =  pd.read_csv(fname, encoding='latin-1')

# PRINTING BORDER AND OUTLINES FOR DATA 
print('======================Input Data Values======================')
print(in_data)
print('=============================================================')

# MOVING THE FILE CONTENT TO ANOTHER VARIABLE SO THAT IT WILL NOT CHANGE ORIGINAL FILE CONTENT
process_data = in_data
process_data

# CHANGING THE FILE CONTENT BY DROPPING THE COLUMNS
process_data.drop('ISO-2-CODE', axis=1, inplace=True)
process_data.drop('ISO-3-Code', axis=1, inplace=True)

# PRINTING THE CHANGED FILE
process_data

# RENAMING THE EXISTING COLUMNS NAME
process_data.rename(columns={'Country':'CountryName'}, inplace=True)
process_data.rename(columns={'ISO-M49':'CountryNumber'}, inplace=True)
process_data

# SET COUNTRY NUMBER AS NEW INDEX
process_data.set_index('CountryNumber', inplace=True)

# SORTING COUNTRY NUMBER IN ASCENDING NUMBER
process_data.sort_values('CountryNumber', axis=0, ascending=True, inplace=True)
print(process_data)

# SORTING COUNTRY NAME IN ASCENDING NAME
process_data.sort_values('CountryName', axis=0, ascending=True, inplace=True)
print(process_data)

# OUTPUT AGREEMENT
out_data=process_data
sOutputFileName='CSV_HORUS_Country_Code.csv'
out_data.to_csv(sOutputFileName, index=True)