# -*- coding: utf-8 -*-
"""Practical_2C.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cT-x_iQDdJkdHPnd-9sjiepY07jCqRs-
"""

# PRACTICAL 2 - CONVERTING DATA TO HORUS
# 2C. JSON TO HORUS
# VIVEKSINGH NEGI - 13-SEP-2022
# UNIVERSITY DEPARTMENT OF INFORMATION TECHNOLOGY

# IMPORTING LIBRARIES 
import pandas as pd

# OPENING THE FILE
sInputFileName='/content/Country_Code.json'
InputData=pd.read_json(sInputFileName, orient='index', encoding="latin-1")

# SHOWING ONLY 5 ARRAYS OF THE FILE DATA
InputData.head()

# MOVING THE FILE CONTENT TO ANOTHER VARIABLE SO THAT IT WILL NOT CHANGE ORIGINAL FILE CONTENT
ProcessData = InputData
ProcessData

# CHANGING THE FILE CONTENT BY DROPPING THE COLUMNS
ProcessData.drop('ISO-2-CODE', axis=1,inplace=True)
ProcessData.drop('ISO-3-Code', axis=1,inplace=True)
ProcessData.head()

# RENAMING THE EXISTING COLUMNS NAME
ProcessData.rename(columns={'Country': 'CountryName'}, inplace=True)
ProcessData.rename(columns={'ISO-M49': 'CountryNumber'}, inplace=True)
ProcessData.head()

# SET COUNTRY NUMBER AS NEW INDEX 
ProcessData.set_index('CountryNumber', inplace=True)

# SORTING COUNTRY NUMBER IN ASCENDING NUMBER
ProcessData.sort_values('CountryNumber', axis=0, ascending=True, inplace=True)
print(ProcessData)

# OUTPUT AGREEMENT
OutputData=ProcessData
sOutputFileName='JSON_HORUS_Country_Code.csv'
OutputData.to_csv(sOutputFileName, index = True)