# -*- coding: utf-8 -*-
"""Practical_5E2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oV5F9gdE0daduDShm_Xn7eoq6_BhtgL_
"""

# 5E Drop col where any element are missing
# Executed by VIVEKSINGH NEGI
# MScIT Part 1 - Sem 1 
# University Department of Information Technology

import sys
import os
import pandas as pd

sOutputFileName = '/content/anymissing.csv'
sInputFileName = '/content/Good-or-Bad.csv'

print('Loading :',sInputFileName)
RawData=pd.read_csv(sInputFileName,header=0)

RawData

print('Rows    :',RawData.shape[0])
print('Columns :',RawData.shape[1])

# Drop columns where any value is missing
TestData=RawData.dropna(axis=1, how='any')

TestData

print('Rows :',TestData.shape[0])
print('Columns :',TestData.shape[1])

TestData.to_csv(sOutputFileName, index = False)