# -*- coding: utf-8 -*-
"""Practical_5E3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yp2erJ9sSGCGypjzCXfnSWE2owy78nAM
"""

# 5E Drop rows where more than 2 values are missing
# Executed by VIVEKSINGH NEGI
# MScIT Part 1 - Sem 1 
# University Department of Information Technology

import sys
import os
import pandas as pd

sInputFileName='/content/Good-or-Bad.csv'
sOutputFileName='/content/morethan2missing.csv'

print('Loading :',sInputFileName)
RawData=pd.read_csv(sInputFileName,header=0)

RawData

print('Rows :',RawData.shape[0])
print('Columns :',RawData.shape[1])

# Drop rows where more than 2 values are missing
TestData=RawData.dropna(thresh=2)

TestData

print('Rows :',TestData.shape[0])
print('Columns :',TestData.shape[1])

TestData.to_csv(sOutputFileName, index = False)