# -*- coding: utf-8 -*-
"""5A4 Assess Good or Bad.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZHHajXZyVr_rWVdqgxKPb-qPrJoRnXIG
"""

import sys
import os
import pandas as pd

InputFileName='Good-or-Bad.csv'
OutputFileName='Good-or-Bad-04.csv'
InputFileDir ='C:/VKHCG/01-Vermeulen/02-Assess/01-EDS/02-Python'
sOutputFileNameA='Good-or-Bad-05-A.csv'
sOutputFileNameB='Good-or-Bad-05-B.csv'
sOutputFileNameC='Good-or-Bad-05-C.csv'
sOutputFileNameD='Good-or-Bad-05-D.csv'
sOutputFileNameE='Good-or-Bad-05-E.csv'
OutputFileDir = 'C:/VKHCG/01-Vermeulen/02-Assess/01-EDS/02-Python'

sInputFileName = InputFileDir + '/' + InputFileName
print('Loading', sInputFileName)

RawData=pd.read_csv(sInputFileName,header=0)
print(RawData)

RawData.shape

# Replace with mean
TestData=RawData.fillna(RawData.mean())
print(TestData)

sOutputFileName=OutputFileDir + '/' + sOutputFileNameA
TestData.to_csv(sOutputFileName, index = False)

# Replace with median
TestData=RawData.fillna(RawData.median())
print(TestData)
sOutputFileName=OutputFileDir + '/' + sOutputFileNameB
TestData.to_csv(sOutputFileName, index = False)

# Replace with min
TestData=RawData.fillna(RawData.min())
print(TestData)
sOutputFileName=OutputFileDir + '/' + sOutputFileNameC
TestData.to_csv(sOutputFileName, index = False)

# Replace with max
TestData=RawData.fillna(RawData.max())
print(TestData)
sOutputFileName=OutputFileDir + '/' + sOutputFileNameD
TestData.to_csv(sOutputFileName, index = False)

