# -*- coding: utf-8 -*-
"""k1-Picking Content for Billboards.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ISm0dseV0K5hMPwJSAWfDWChTkyuiSGT
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install folium

import sys 
import os
import pandas as pd
from folium.plugins import FastMarkerCluster, HeatMap 
from folium import Marker, Map
import webbrowser 

sFileName='Retrieve_DE_Billboard_Locations.csv' 
df = pd.read_csv(sFileName,header=0,low_memory=False, encoding="latin-1")
df.fillna(value=0, inplace=True) 
print(df.shape)
df.head()

################################################################
t=0
for i in range(df.shape[0]): 
    try:
        sLongitude=df["Longitude"][i] 
        sLongitude=float(sLongitude)
    except Exception: 
        sLongitude=float(0.0)
    try:
        sLatitude=df["Latitude"][i] 
        sLatitude=float(sLatitude)
    except Exception: 
        sLatitude=float(0.0)
    try:
        sDescription=df["Place_Name"][i] + ' (' + df["Country"][i]+')'
    except Exception: 
        sDescription='VKHCG'
    if sLongitude != 0.0 and sLatitude != 0.0: 
        DataClusterList=list([sLatitude, sLongitude]) 
        DataPointList=list([sLatitude, sLongitude, sDescription]) 
        t+=1
        if t==1:
            DataCluster=[DataClusterList] 
            DataPoint=[DataPointList]
        else:
            DataCluster.append(DataClusterList) 
            DataPoint.append(DataPointList)
data=DataCluster 
pins=pd.DataFrame(DataPoint)
pins.columns = [ 'Latitude','Longitude','Description'] 
################################################################
stops_map1 = Map(location=[48.1459806, 11.4985484], zoom_start=5) 
marker_cluster = FastMarkerCluster(data).add_to(stops_map1)
sFileNameHtml='Billboard1.html' 
stops_map1.save(sFileNameHtml)
webbrowser.open('file://' + os.path.realpath(sFileNameHtml)) 
################################################################
stops_map2 = Map(location=[48.1459806, 11.4985484], zoom_start=5) 
for name, row in pins.iloc[:100].iterrows():
    Marker([row["Latitude"],row["Longitude"]], popup=row["Description"]).add_to(stops_map2) 
sFileNameHtml='Billboard2.html' 
stops_map2.save(sFileNameHtml)
webbrowser.open('file://' + os.path.realpath(sFileNameHtml)) 
################################################################
stops_heatmap = Map(location=[48.1459806, 11.4985484], zoom_start=5) 
stops_heatmap.add_child(HeatMap([[row["Latitude"], row["Longitude"]] for name, row in pins.iloc[:100].iterrows()]))
sFileNameHtml='Billboard_heatmap.html' 
stops_heatmap.save(sFileNameHtml)
webbrowser.open('file://' + os.path.realpath(sFileNameHtml)) 
################################################################ 
print('### Done!! ############################################') 
################################################################

