# -*- coding: utf-8 -*-
"""Retrieve-Country-Currency.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v3vKLurhPnRbTzcJE-JMCgwkqvK5MSAh
"""

import os
import pandas as pd
import sys

#pip install xlrd

InputFileName = 'Country_Currency.xls'
InputFileDir = 'C:/VKHCG/04-Clark/01-Retrieve'
OutputFileName = 'Retrieve_Country_Currency.csv'
OutputFileDir = 'C:/VKHCG/04-Clark/01-Retrieve'

sInputFileName = InputFileDir + '/' + InputFileName
print(sInputFileName)
sOutputFileName= OutputFileDir + '/' + OutputFileName
print(sOutputFileName)

CurrencyRawData = pd.read_excel(sInputFileName, sheet_name = "Data")
CurrencyRawData.shape

sColumns = ['Country or territory', 'Currency', 'ISO-4217']
CurrencyData = CurrencyRawData[sColumns]

print(CurrencyData)

CurrencyData.rename(columns={'Country or territory': 'Country', 'ISO-4217':
'CurrencyCode'}, inplace=True)
CurrencyData.dropna(subset=['Currency'],inplace=True)
CurrencyData.head()

CurrencyData.shape

CurrencyData['Country'] = CurrencyData['Country'].map(lambda x: x.strip())
CurrencyData['Currency'] = CurrencyData['Currency'].map(lambda x:
x.strip())
CurrencyData['CurrencyCode'] = CurrencyData['CurrencyCode'].map(lambda x:
x.strip())

print(CurrencyData)

CurrencyData.to_csv(sOutputFileName, index = False)